version: "3.8"

volumes: 
    proeventos_data:

networks: 
    mysqlNET:
    proeventosNET:

services: 

    mysql:
        image: "mysql:5.7"
        container_name: mysql
        ports: 
            - "3306:3306"
        volumes: 
            - proeventos_data:/var/lib/mysql
            - ./scripts_db:/docker-entrypoint-initdb.d
        networks: 
            - mysqlNET
        environment:            
            - MYSQL_PASSWORD=admin123 
            - MYSQL_ROOT_PASSWORD=admin123 
            - MYSQL_ROOT_HOST=%
            - bind-address=0.0.0.0 
    
    api:
        build:
            context: .
            dockerfile: Dockerfile.V2
        container_name: api
        networks: 
            - mysqlNET
            - proeventosNET
        ports: 
            - 5000:80
        environment: 
            - DBHOST=mysql
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on: 
            - mysql